#include "io-lite.h"

@include(managed-struct.hup)

@ManagedStruct(struct {
    int id;
    float value;
}) AnonBox;

AnonBox create_anon(int id, float value) {
    AnonBox a;
    a->id = id;
    a->value = value;
    return a;
}

int main() {
    AnonBox a1 = create_anon(1, 3.14);
    int ok = (a1->id == 1);
    
    AnonBox a2 = a1; // Should retain
    ok &= (_Managed_ref_count(a1) == 2);
    
    printf("%s (refs=%d)\n", ok ? "PASS":"FAIL", _Managed_ref_count(a1));
    return 0;
}
