#include "io-lite.h"

@define DefRef(label) {
    const target = upp.nextNode();
    upp.withReferences(target, (ref, h) => {
        const kind = h.isDeclaration() ? "Declare" : "Ref";
        return upp.code`/* ${kind} ${label} */ ${ref}`;
    });
}

@DefRef("fn") void fn(int i){}
@DefRef("MyType") typedef int MyType;

int main() {
    @DefRef("x") MyType x = 10;
    x = 5;
    fn(x);
    return 0;
}