#include "io-lite.h"

@include(defer.hup)

int some_condition;
int main() {
    char *str1 = malloc(100);
    @defer { free(str1); str1 = NULL; }
    char *str2;

    {
        char *nested = malloc(100);
        @defer { free(nested); nested = NULL; }
        if (some_condition) {
            // should defer here, str1
            return 1;
        }
    }
    str2 = malloc(100);
    @defer { free(str2); str2 = NULL; }

    // should defer here, str2 then str1
    return 0;
}
