#include "io-lite.h"

@include(method.hup)

typedef struct {
    int x;
    int y;
} Point;

@define Point() {
    return "@useCreate(Point)";
}

@method(Point) void print(Point *p) {
    printf("Point(%d, %d)\n", p->x, p->y);
}

@method(Point) void Create(Point *p) {
    printf("Point created(%d, %d)\n", p->x, p->y);
}

int main() {
    @Point p;
    @Point q = { .x = 5, .y = 9 };
    p.print();
    q.print();
    return 0;
}
