@define retype() {
    upp.registerTransformRule((root, helpers) => {
        helpers.matchReplace(root, `$type $x__identifier = $val__number_literal;`, ({ type, x, val }) => {
            return upp.codeTree`${type} ${x} = (${type.text})${val};`;
        }, { deep: true });
    });
}

@retype;

int foo = 100;
int bar = 200;

void f() {
    char * bar = "hello";
}

int main() {
    int bar = 5;
    char baz = 'a';
    return 0;
}
