
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rootDir = path.resolve(__dirname, '..');
const outputFile = path.join(rootDir, 'vsix', 'upp.d.ts');
const inputFile = path.join(rootDir, 'src', 'upp_helpers_c.ts');

console.log('Generating upp.d.ts...');

try {
    // Generate dts using dts-bundle-generator
    // We use npx to avoid adding a dev dependency if not present, but it's recommended to add it.
    // Ensure we are in rootDir
    execSync(`npx -y dts-bundle-generator -o "${outputFile}" "${inputFile}"`, {
        cwd: rootDir,
        stdio: 'inherit'
    });

    let content = fs.readFileSync(outputFile, 'utf8');

    // Post-process the content
    // 1. Wrap in parser namespace shim
    const parserShim = `
declare namespace Parser {
    type Tree = any;
    type SyntaxNode = any;
}
`;

    // 2. Wrap in upp namespace
    const uppNamespaceStart = `
declare namespace upp_types {
`;
    const uppNamespaceEnd = `
} // End namespace upp_types

declare var upp: upp_types.UppHelpersC & {
    registry: upp_types.Registry;
    path: any;
    invocation: upp_types.Invocation;
};
`;

    // 3. Post-process the content
    // Strip imports
    content = content.replace(/^import.*;?\r?\n/gm, '');

    // Strip 'export declare class' -> 'export class'
    content = content.replace(/export declare class/g, 'export class');

    // Strip top-level 'declare class' (not exported) -> 'class' or 'export class'
    content = content.replace(/^declare class/gm, 'export class');

    // Fix: cannot use namespace 'Parser' as a type
    content = content.replace(/Parser\.(Tree|SyntaxNode)/g, 'any');
    content = content.replace(/parser: Parser;/g, 'parser: any;');

    // 4. Remove 'export {}' at the end if present
    content = content.replace(/export\s*{\s*};\s*$/m, '');

    // Combine everything
    const finalContent = `// Generated by scripts/generate_vscode_dts.js
${parserShim}
${uppNamespaceStart}
${content}
${uppNamespaceEnd}
`;

    fs.writeFileSync(outputFile, finalContent);
    console.log(`Successfully generated ${outputFile}`);

} catch (error) {
    console.error('Failed to generate upp.d.ts:', error);
    process.exit(1);
}
